:data-uri:
:noaudio:

== Types Of Event Consumption Patterns

* Volatile
** The event needs to be disseminated to all consumers online at time of publication. 
** Not persisted.

* Durable
** Events stored durably until read by all registered consumers. 
** Traditional store-and-forward brokers.

* Replayable
** Events stored durably for specific period of time or storage capacity.
** Consumers can move back and forth of the stream.

ifdef::showscript[]

Transcript:

As events are generated in one of the Event-driven Architecture components and the notifications placed in the channel, the communication pattern used to share then defines also the nature of the messages. For the purpose of better understanding, we have classified events in 3 major types. This event types allow software architects to choose adequate event-driven architecture component implementations

Volatiles - room temperature - audience is not crucial in this type
Consumable needs to get feedback from consumers 
Replayable - auditable information



endif::showscript[]
