:data-uri:
:noaudio:

== Service Registry Use Cases

* Schema Registry
** Schema registry for Kafka serializers/deserializers

* API Designs
** API specification registry for API consumers

* Shared Data Types
** Shared data types and schemas across API and Event-Driven Architectures

ifdef::showscript[]

Transcript:

API Registry
The key use-case for the Apicurio community, an API Registry is a system that allows users to register their API designs (e.g. OpenAPI or AsyncAPI files) so that potential API consumers can do the following:

Browse/search the list of APIs available in production
View details about a single available API
Learn how to use an API (via generated documentation)
Generate Client SDKs for an API

Schema Registry
In the messaging and event streaming world, data that are published to topics and queues often must be serialized or validated using a Schema (e.g. Apache Avro, JSON Schema, or Google protocol buffers). Schemas can be packaged in each application, but it is often a better architectural pattern to instead register them in an external system and then referenced from each application. This allows the following:

Decoupling of schemas from producers and consumers
Potential to upgrade producers without upgrading consumers
Central location to track all Schemas used in production
Document the data format required for each topic/queue
Centralized control of data format (schema) evolution

endif::showscript[]
