:data-uri:
:noaudio:

== Instrumenting Applications With Microprofile Metrics Annotations

* Developers can add instrumentation to their code using annotations

[cols="2",caption=""]
|====
|Amnotation
|Description

| @Timed
| Denotes a timer, which tracks duration of the annotated object.

| @SimplyTimed 
| Denotes a simple timer, which tracks duration and invocations of the annotated object.

| @Metered
| Denotes a meter, which tracks the frequency of invocations of the annotated object.

| @Gauge
| Denotes a gauge, which samples the value of the annotated object.

| _Others_
| ...
|====

* More details are available at:  https://microprofile.io/project/eclipse/microprofile-metrics

ifdef::showscript[]

Transcript:

@Timed produces two metrics: the total count of invocations of the annotated method, and the total time spent invoking the method. These metrics allow to calculate throughput (how many invocations per time unit) and latency (how long does an invocation take).

@SimplyTimed doesn’t perform mean and distribution calculations. It only calculates hit count and time spent on a method. @SimplyTimed is a “simple” version of @Timed that reduces calculation time, as these calculations can be performed by Prometheus with the raw data from @SimplyTimed.

endif::showscript[]
