  - hosts: all
    vars_prompt:
    - name: username
      prompt: What is your Quay's username?
      private: no
    - name: password
      prompt: What is your Quay's password?
    tasks:
    - debug:
        msg: 'Username: {{ username }}'
