- hosts: localhost
  connection: local
  vars:
    base_path: ../../content/
    source: pages
    root: modules/ROOT
    destination: build
    path_origin: https://github.com/redhat-gpe/cnd_advanced_v2
  vars_prompt:
    - name: indexName
      prompt: What is your main file name (index.adoc)? Provide only the name. Ex. 01_1_Environment_Setup_Lab.adoc
      private: no
  
  tasks:
  
  - name: Download source code from repo
    shell: (git clone "{{ path_origin }}" tmp; mv temp/.git code/.git)
    register: download
    failed_when: download.rc == "already exists and is not an empty directory" not in download.rc

  - name: moving lab docs
    shell: (cp -r tmp/modules/  "{{ base_path }}{{ root }}"/pages/) 
    register: cleaning
  - debug: msg="{{ cleaning.rc }}"
  
  #- name: Create index.adoc
   # shell: (find . "{{ base_path }}{{ root }}"/pages/ -name f  \("{{ indexName }}"\) -exec mv -P {} "{{ base_path }}{{ root }}"/index.adoc \;)
    #register: indexFile
  #- debug: msg="{{ indexFile.stdout }}"

  - name: Move images to content folder
    shell: (find . "{{ base_path }}{{ root }}"/pages/ -type f \( -iname \*.jpg -o -iname \*.png \) -exec cp -P {} "{{ base_path }}{{ root }}"/images \;) 
    register: images
  - debug: msg="{{ images.rc }}"


 # - name: moving lab docs
  #  shell: (find . "{{ base_path }}{{ root }}"/images -type f \( -iname \*.jpg -o -iname \*.png \) -exec rm -P {} \;) 
   # register: docs
  #- debug: msg="{{ cleaning.rc }}"


  - name: Run Antora for adoc files
    shell: (antora --fetch antora-playbook.yml)
    register: doc
  - debug: msg="{{ doc.stdout }}"

