- hosts: localhost
  connection: local
  vars:
    base_path: ../../
    source: pages
    root: modules/ROOT
    destination: build
    path_origin: https://github.com/redhat-gpe/cnd_advanced_v2
    git_msg: "Generated content"
    path_tmp: tmp
  vars_prompt:
    - name: indexName
      prompt: What is your main file name (index.adoc)? Provide only the name. Ex. 01_1_Environment_Setup_Lab.adoc
      private: no
    - name: updateRepo
      prompt: Do you need to download your repo? Y/N
      private: no  
  
  tasks:
  
  - name: Download source code from repo
    shell: (git clone "{{ path_origin }}" "{{ path_tmp }}"; mv temp/.git code/.git)
    register: download
    failed_when: download.rc == "already exists and is not an empty directory" not in download.rc
    when: "{{ updateRepo == 'Y' }}"

  - name: moving lab docs
    shell: (find . "{{ path_tmp }}" -type f \( -iname \*_Lab.adoc  \) -exec cp -P {} "{{ base_path }}{{ root }}/pages/" \;) 
    when: "{{ updateRepo == 'Y' }}"

  
  - name: Create index.adoc
    shell:  (find "{{ base_path }}{{ root }}/pages" -name "{{ indexName }}" -exec mv {} "{{ base_path }}{{ root }}/index.adoc" \;)
    #register: indexFile
  #- debug: msg="{{ indexFile.stdout }}"

  - name: Move images to content folder
    shell: (find . "{{ base_path }}{{ root }}"/pages/ -type f \( -iname \*.jpg -o -iname \*.png \) -exec cp -P {} "{{ base_path }}{{ root }}"/images \;) 
    register: images
  - debug: msg="{{ images.rc }}"
    when: "{{ updateRepo == 'Y' }}"


  - name: Updating content in the repository (Antora)
    shell: (rootPath=`pwd`;git add $rootPath/../../"{{ root }}"; git commit -m "{{ git_msg }}"; git push)

  - name: Run Antora for adoc files
    shell: (cd ../.. ;antora --fetch antora-playbook.yml)
    register: doc
  - debug: msg="{{ doc.stdout }}"

