- hosts: localhost
  connection: local
  vars_files:
    - ../input/input_var.yml
  environment:
  KUBECONFIG: "{{ lookup('env', 'HOME') }}/openstack-upi/auth/kubeconfig"
  INFRA_ID: "INFRA_ID=$(jq -r .infraID {{ lookup('env', 'HOME') }}/openstack-upi/metadata.json)"
  tasks:
    - name: Create project
      oc:
        state: present
        inline:
          kind: ProjectRequest
          metadata:
            name: classroom
          displayName: Classroom Project
          description: Classroom Project 
    - name: Create container image
      template:
        src: "./templates/buildconfig.yaml.j2"
        dest: "$HOME/buildconfig.yaml"
      vars:
        GUID: "{{ lookup('env', 'GUID') }}"

