- hosts: localhost
  connection: local
  tasks:
  - name: docker login
    community.docker.docker_login:
      registry: quay.io
      username: varodrig@redhat.com
      password: 
      config_path: /tmp/.mydockercfg
 
  - name: build the UI image
    community.general.docker_image:
      build: 
       path: ../
      name: "quay.io/varodrig/containers-lab:latest"
      push: yes
      source: build
  - name: Create the terminal container
    community.general.docker_container:
      name: terminal
      image: "quay.io/varodrig/containers-lab:latest"
      ports:
      # Publish container port 9000 as host port 8080
       - "10080:10080"

       