- hosts: localhost
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your Quay's username?
      private: no
    - name: password
      prompt: What is your Quay's password?
    - name: organization
      prompt: organization/user in Quay?
      private: no
  vars:
    app_path: "../../frontend/web_app"
    image_registry_path: "quay.io/{{ organization }}/containers-lab-frontend:latest"
    container_name: "frontend"    
  tasks:
  - debug:
      msg: 'Username: {{ username }}'

  - name: Get infos on container
    community.docker.docker_container_info:
      name: "{{ container_name }}"
    register: r_info_container

  - name: Does container exist?
    ansible.builtin.debug:
      msg: "The container {{ 'exists' if r_info_container.exists else 'does not exist' }}"

  - name: Stop the container if exists before creation
    community.general.docker_container:
      name: "{{ container_name }}"
      state: absent
      force_kill: yes
    when: "{{ r_info_container.exists }}"
    register: r_stop_container

  - name: Remove image
    command: docker image rm "{{ image_registry_path }}"
    register: r_remove_image
    failed_when: r_remove_image.rc == "No such" not in r_remove_image.stdout
  - debug: msg="{{ r_remove_image.stdout }}"

  - name: Build the frontend image
    community.general.docker_image:
      build: 
        path: "{{ app_path }}"
      name: "{{ image_registry_path }}"
      push: yes
      source: build
    register: r_build_image
  
  - name: Create the frontend container
    community.general.docker_container:
      name: "{{ container_name }}"
      image: "{{ image_registry_path }}"
      pull: yes
      ports:
       - "80:80"
    register: r_create_container
  - debug: msg="{{ r_create_container }}"

       