- import_playbook: common.yml
- hosts: localhost
  connection: local
  vars_files:
    - ../input/input.yml
  vars:
    image_registry_path: "quay.io/varodrig/containers-lab:latest"
  tasks:
  - name: input_list
    ansible.builtin.debug:
      msg: "{{ item }}"
    with_items: "{{ assets }}"
  - name: input_list -> loop
    ansible.builtin.debug:
      msg: "{{ assets[1].source }}"
    loop:
      -  "{{ assets[1]}}"
  - name: docker login
    community.docker.docker_login:
      registry: quay.io
      username: "{{ username }}"
      password: "{{ password }}"
      config_path: /tmp/.mydockercfg
  - name: build an image
    community.general.docker_image:
      build: 
       path: "{{ assets[1].source }}"
      name: "{{ image_registry_path }}"
      push: yes
      source: build
  - name: Create the content container
    community.general.docker_container:
      name: docs
      image: "{{ image_registry_path }}"
      ports:
      # Publish container port 9000 as host port 8080
       - "{{ assets[1].ports[0] }}"