- import_playbook: common.yml
- hosts: localhost
  connection: local
  vars:
    app_path: "../../frontend/web_app"
    image_registry_path: "quay.io/varodrig/containers-lab-frontend:latest"
  tasks:
  - name: docker login
    community.docker.docker_login:
      registry: quay.io
      username: "{{ username }}"
      password: "{{ password }}"
      config_path: /tmp/.mydockercfg
  - name: build the frontend image
    community.general.docker_image:
      build: 
       path: "{{ app_path }}"
      name: "{{ image_registry_path }}"
      push: yes
      source: build
  - name: Create the frontend container
    community.general.docker_container:
      name: frontend
      image: "{{ image_registry_path }}"
      ports:
      # Publish container port 9000 as host port 8080
       - "80:80"

       