- hosts: localhost
  connection: local
  vars_files:
    - ../input/input.yml
  vars:
    app_path: "../content/web_app"
    image_registry_path: "quay.io/varodrig/containers-lab-frontend:latest"
  tasks:
  - name: input_list
    ansible.builtin.debug:
      msg: "{{ item }}"
    with_items: "{{ assets }}"
  - name: input_list -> loop
    ansible.builtin.debug:
      msg: "{{ assets[1].name}}"
    loop:
      -  "{{ assets[1]}}"
  - name: docker login
    community.docker.docker_login:
      registry: quay.io
      username: varodrig@redhat.com
      password: 
      config_path: /tmp/.mydockercfg
  - name: build an image
    community.general.docker_image:
      build: 
       path: "{{ assets[1]}}"
      name: "quay.io/varodrig/containers-lab:latest"
      push: yes
      source: build
  - name: Create the content container
    community.general.docker_container:
      name: docs
      image: "quay.io/varodrig/containers-lab:latest"
      ports:
      # Publish container port 9000 as host port 8080
       - "{{ assets[1].ports[0]}}"