:data-uri:
:noaudio:

== Why Event-Driven Architecture?

* Mirrors the real world
** The real world is event-driven. 
** Systems generate and respond to events in everyday life, e.g., the human central nervous system.

* Reduced coupling
** Traditional RPC-style service architecture results in tightly-bound services. 
** Changes to the application flow typically require service code changes. EDA allows new functionality to be added by adding services that consume existing event streams.

* Encapsulation
** Microservices concepts have grown in popularity due to the ability for service teams to develop services in isolation. 
** EDA means that service designers need not be aware of how events are consumed.

ifdef::showscript[]

Transcript:

This decoupled nature of event handling is at the heart of event-driven microservices.

Event-driven microservices pass messages through messaging middleware to communicate amongst the services, thereby decoupling the components and allowing events to be observed, recorded, and acted upon. The messaging backend provides the ability to do advanced distributed actions like flow control, delivery guarantees, and persistence for high availability.

endif::showscript[]
