:data-uri:
:noaudio:

== Service Registry Compatibility Rules

* Backward Compatibility
** New version of the artifact would be compatible with previous versions of that artifact.
** Records that use the previous version can be read using the new artifact.

* Forward Compatibility
** Existing artifact is compatible with future versions of that artifact.
** Records that use the new artifact can still be retrieved using previous version.


ifdef::showscript[]

Transcript:

Each rule is simply a name and some optional configuration. The registry storage maintains the list of rules for each artifact and the list of global rules. Each rule in the list consists of a name and a set of configuration properties, which are specific to the rule implementation. For example, a validation rule might use a Map<String,String>, or a compatibility rule might use a single property of BACKWARD for compatibility with existing versions.

A rule is provided with the content of the current version of the artifact (if one exists) and the new version of the artifact being added. The rule implementation returns true or false depending on whether the artifact passes the rule. If not, the registry reports the reason why in an HTTP error response. Some rules might not use the previous version of the content. For example, compatibility rules use previous versions, but syntax or semantic validity rules do not.

endif::showscript[]
