:data-uri:
:noaudio:

== Camel K and Knative

* Write code in Camel DSL
* Interact with Openshift Serverless components in background
* `kamel run` manages mechanics
* Camel K sets up subscriptions and routes
* Kamel binary creates YAML config from DSL code

ifdef::showscript[]

Transcript:
Camel K allows users to write code in the Camel DSL that they are familiar with and interact with OpenShift Serverless components in the background. After the user writes the route in a Groovy file, "kamel run" manages everything else. It even guesses dependencies based on URI prefixes. In case a dependency is missed, all of the options can be configured on the command line. Camel K sets up Subscriptions and Routes between components automatically. Currently, it cannot create Channels for you, but that may come in the future.

The Camel DSL is converted to a YAML configuration by the Kamel binary for deployment on Kubernetes. It is not recommended to use the binary in a production environment. Instead, it is recommended to promote the YAML configuration that is created.

endif::showscript[]
