:data-uri:
:noaudio:

== Application Monitoring

.Prometheus

* Open source monitoring solution

* Inspired by Google's Borgmon monitoring tool

* Graduated project of Cloud Native Computing Foundation
** Second after Kubernetes

* Inclusive monitoring: Blackbox/whitebox, client libraries

* Time series collection implemented via pull model over HTTP

* Multi-dimensional data model with time series data identified by metric name and key/value pairs

* Powerful query language

** Multiply, add, aggregate, join, compute quantiles


ifdef::showscript[]

Transcript:

Prometheus is an open source monitoring solution. It was inspired by Google's Borgmon monitoring tool.

Prometheus is a graduated project of the Cloud Native Computing Foundation. It was the second project after Kubernetes.

Prometheus provides inclusive monitoring that incorporates both blackbox and whitebox, as well as client libraries. Time series collection is implemented using a pull model over HTTP.

Prometheus has a multi-dimensional data model with time series data identified by metric name and key/value pairs.

Prometheus also includes a powerful query language. Some supported operations include multiply, add, aggregate, join, and compute quantiles.

endif::showscript[]
